//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventories
{
    using System;
    using System.Collections.Generic;
    
    public partial class useraccount
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> roleid { get; set; }
        public string code { get; set; }
    
        public virtual role role { get; set; }
        public virtual useraccount useraccount1 { get; set; }
        public virtual useraccount useraccount2 { get; set; }
    }
}
