//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventories
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinformation
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string zipcode { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> managerid { get; set; }
    }
}
